### ISSUE TITLE
type' object is not subscriptable

### ISSUE THREAD

**Issue by Pymous64** [snipem/gt7dashboard#18]
Hello,
When I tried to launch, I have this error message :

> 
> 2023-09-03 15:55:58,681 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x7fedbac9c880>: 'type' object is not subscriptable
> File 'gt7lap.py', line 83, in Lap:
> def get_data_dict(self, distance_mode=True) -> dict[str, list]: Traceback (most recent call last):
>   File "/home/user/.local/lib/python3.8/site-packages/bokeh/application/handlers/code_runner.py", line 231, in run
>     exec(self._code, module.__dict__)
>   File "/home/user/volant/gt7dashboard/main.py", line 24, in <module>
>     from gt7dashboard import gt7communication, gt7diagrams, gt7help, gt7helper, gt7lap
>   File "/home/user/volant/gt7dashboard/gt7dashboard/gt7communication.py", line 14, in <module>
>     from gt7dashboard.gt7helper import seconds_to_lap_time
>   File "/home/user/volant/gt7dashboard/gt7dashboard/gt7helper.py", line 18, in <module>
>     from gt7dashboard.gt7lap import Lap
>   File "/home/user/volant/gt7dashboard/gt7dashboard/gt7lap.py", line 4, in <module>
>     class Lap:
>   File "/home/user/volant/gt7dashboard/gt7dashboard/gt7lap.py", line 83, in Lap
>     def get_data_dict(self, distance_mode=True) -> dict[str, list]:
> TypeError: 'type' object is not subscriptable

My level in python is not high enough to find a solution.
My OS is Ubuntu 20.04 with Python 3.8.10

Thank you for this great work.

**Comment by snipem** [comment]
What version are you using? Are you starting from a blank state?

**Comment by Pymous64** [comment]
I use gt7dashboard version 1.1. I have launch from my session after the install of python dependency. All requirements are satisfied.
I have those errors when I open the web page in navigator.
You think I must use it on Docker ?
