### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Mdeuschl** [snipem/gt7dashboard#20]
Sorry if this is not the right place to report but I don't know better.

I keep getting errors when trying to install… What do I do? Do I have to look for fortran now? Do I need to install SSL Certificates? 
Tbh I'd wish installing this would be easier.

Thanks for looking into this…

Yours
Matt

> ../meson.build:57:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]

And further down:

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>  File "gt7dashboard-main/helper/download_cars_csv.py", line 6, in <module>
>    urllib.request.urlretrieve(url, filename)
>
>  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1347, in do_open
>    raise URLError(err)
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>
> /Library/Frameworks/Python.framework/Versions/3.12/bin/python3: No module named bokeh

**Comment by afranco69** [comment]
Just as a comment. I wanted to install in an old laptop, so windows (10) wouldn't be an option. I'm not an expert on Linux. First I tried the latest Debian build. Unfortunately, I run into python dependencies problems. So, Now I'm using Ubuntu. I just had to apt install python3-pip and everything worked as it should. Great work. Kudos!!

**Comment by SensLike** [comment]
> Just as a comment. I wanted to install in an old laptop, so windows (10) wouldn't be an option. I'm not an expert on Linux. First I tried the latest Debian build. Unfortunately, I run into python dependencies problems. So, Now I'm using Ubuntu. I just had to apt install python3-pip and everything worked as it should. Great work. Kudos!!

Hmm I can here to ask if there was a possibilty to run it on a Raspberry, I tried yesterday but failed over and over again.. With my little knowledge I was running into several errors. Now with your submission I think I'll try again with a Ubuntu build isntead of Debian..
